// Mocks generated by Mockito 5.4.6 from annotations
// in tkit/test/features/settings/domain/usecases/watch_settings_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tkit/core/errors/failure.dart' as _i5;
import 'package:tkit/features/settings/domain/entities/app_settings.dart'
    as _i6;
import 'package:tkit/features/settings/domain/repositories/i_settings_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ISettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISettingsRepository extends _i1.Mock
    implements _i3.ISettingsRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AppSettings>> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.AppSettings>>.value(
                  _FakeEither_0<_i5.Failure, _i6.AppSettings>(
                    this,
                    Invocation.method(#getSettings, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i6.AppSettings>>.value(
                  _FakeEither_0<_i5.Failure, _i6.AppSettings>(
                    this,
                    Invocation.method(#getSettings, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AppSettings>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateSettings(
    _i6.AppSettings? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSettings, [settings]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateSettings, [settings]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#updateSettings, [settings]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Stream<_i6.AppSettings> watchSettings() =>
      (super.noSuchMethod(
            Invocation.method(#watchSettings, []),
            returnValue: _i4.Stream<_i6.AppSettings>.empty(),
            returnValueForMissingStub: _i4.Stream<_i6.AppSettings>.empty(),
          )
          as _i4.Stream<_i6.AppSettings>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> clearSettings() =>
      (super.noSuchMethod(
            Invocation.method(#clearSettings, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#clearSettings, []),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#clearSettings, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
